services:
  # Laravel PHP-FPM
  laravel-php-nginx-tcp:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: laravel-php-nginx-tcp
    restart: unless-stopped
    working_dir: /var/www/laravel
    env_file:
      - .env.docker
    volumes:
      - ./src:/var/www/laravel
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
    networks:
      - laravel-php-nginx-tcp-network
    healthcheck:
      test: [ "CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Веб-сервер Nginx
  laravel-nginx-tcp:
    image: nginx:alpine
    container_name: laravel-nginx-tcp
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/laravel
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel-php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      laravel-php-nginx-tcp:
        condition: service_healthy

  # База данных PostgreSQL 17
  laravel-postgres-nginx-tcp:
    image: postgres:17-alpine
    container_name: laravel-postgres-nginx-tcp
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Веб-интерфейс pgAdmin
  laravel-pgadmin-nginx-tcp:
    image: dpage/pgadmin4:latest
    container_name: laravel-pgadmin-nginx-tcp
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "8080:80"
    networks:
      - laravel-php-nginx-tcp-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      laravel-postgres-nginx-tcp:
        condition: service_healthy

volumes:
  postgres-data:

networks:
  laravel-php-nginx-tcp-network:
    driver: bridge